const sdgs = [
  "assets/icons/goal1.png",
  "assets/icons/goal2.png",
  "assets/icons/goal3.png",
  "assets/icons/goal4.png",
  "assets/icons/goal5.png",
  "assets/icons/goal6.png",
  "assets/icons/goal7.png",
  "assets/icons/goal8.png",
  "assets/icons/goal9.png",
  "assets/icons/goal10.png",
  "assets/icons/goal11.png",
  "assets/icons/goal12.png",
  "assets/icons/goal13.png",
  "assets/icons/goal14.png",
  "assets/icons/goal15.png",
  "assets/icons/goal16.png",
  "assets/icons/goal17.png",
];

const sdgTitles = [
  "GOAL 1: No Poverty",
  "GOAL 2: Zero Hunger",
  "GOAL 3: Good Health and Well-being",
  "GOAL 4: Quality Education",
  "GOAL 5: Gender Equality",
  "GOAL 6: Clean Water and Sanitation",
  "GOAL 7: Affordable and Clean Energy",
  "GOAL 8: Decent Work and Economic Growth",
  "GOAL 9: Industry, Innovation and Infrastructure",
  "GOAL 10: Reduced Inequality",
  "GOAL 11: Sustainable Cities and Communities",
  "GOAL 12: Responsible Consumption and Production",
  "GOAL 13: Climate Action",
  "GOAL 14: Life Below Water",
  "GOAL 15: Life on Land",
  "GOAL 16: Peace and Justice Strong Institutions",
  "GOAL 17: Partnerships to achieve the Goal"
];
