name: matchub_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  country_provider: ^0.0.1
  # json_model: ^0.0.2
  build_runner: ^1.0.0
  # json_serializable: ^2.0.0
  # json_annotation: ^3.0.0
  mvc_pattern: ^6.5.0
  connectivity: ^0.4.9+2
  shared_preferences: ^0.5.7+3
  http: ^0.12.1
  intl: ^0.16.1
  provider: ^3.0.0
  path_provider: ^1.1.0
  drag_select_grid_view: ^0.3.1
  flutter_staggered_grid_view: "^0.3.2"
  path: ^1.6.2
  fcharts: ^0.0.11
  flutter_datetime_picker: ^1.4.0
  flutter_tags: "^0.4.8+2"
  flutter_launcher_icons: ^0.8.0
  international_phone_input: ^1.0.4
  country_list_pick: 1.0.0+9
  flushbar: ^1.10.4
  carousel_slider: ^2.2.1
  badges: ^1.1.3
  file_picker: ^2.0.0
  image_cropper: 1.0.2
  image_picker: ^0.6.7+12
  password_strength: ^0.1.2
  cached_network_image: ^2.2.0+1
  boardview: ^0.1.0
  slide_countdown_clock: ^1.0.3
  shimmer: ^1.1.1
  share: ^0.6.4+3
  open_file: ^3.0.1
  url_launcher: ^5.6.0
  readmore: ^1.0.0
  date_format: ^1.0.9
  string_to_hex: ^0.2.1+30
  bubble_tab_indicator: ^0.1.4
  rxdart: ^0.24.1
  video_thumbnail: ^0.2.2
  video_player: ^0.11.1+2

  date_time_picker: ^1.0.2
  flutter_animation_progress_bar: ^1.0.5
  toast: ^0.1.5
  ticket_pass_package: ^0.1.0
  percent_indicator: "^2.1.7+2"
  liquid_progress_indicator: ^0.3.2
  smooth_page_indicator: ^0.2.0
  speech_to_text: ^2.7.0
  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^3.2.2
  avatar_glow: ^1.2.0
  loading_overlay: ^0.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_slidable: ^0.5.7
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  dotted_border: ^1.0.6
  step_progress_indicator: ^0.2.4+7
  #Firebase
  firebase_core: "0.5.0"
  cloud_firestore: ^0.14.0+2
  # firebase_auth: 0.18.0+1
  firebase_auth: 0.18.0+1
  firebase_messaging: ^7.0.2
  flutter_local_notifications: ^1.4.4+5

  #Security
  local_auth: ^0.6.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Boorsok
      fonts:
        - asset: assets/fonts/boorsok/boorsok.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Thin.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-Light.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
